# Generated by Django 5.1.4 on 2024-12-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroAI', '0003_rename_is_staff_registeruser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeruser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
