# Generated by Django 5.1.4 on 2024-12-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroAI', '0004_rename_is_admin_registeruser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
