# Generated by Django 5.1.4 on 2025-01-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroAI', '0006_alter_registeruser_is_staff'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disorder', models.CharField(max_length=10)),
                ('exercise', models.CharField(max_length=30)),
                ('meditation', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='score',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercisedetails',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='scoredetail',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='DisorderSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeuroAI.disorder')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeuroAI.questions')),
            ],
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='ExerciseDetails',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ScoreDetails',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
