# Generated by Django 5.1.4 on 2025-01-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroAI', '0008_alter_response_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NeuroAI.questions'),
            preserve_default=False,
        ),
    ]
