# Generated by Django 5.1.4 on 2024-12-26 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(max_length=100)),
                ('meditation', models.CharField(max_length=100)),
                ('exercise', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(choices=[('0-3', '0-3'), ('4-7', '4-7'), ('8-10', '8-10')], max_length=10)),
                ('level', models.CharField(choices=[('Mild Symptoms', 'Mild Symptoms'), ('Moderate Symptoms', 'Moderate Symptoms'), ('Severe Symptoms', 'Severe Symptoms')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('occupation', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeuroAI.condition')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercisedetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='NeuroAI.exercisedetails')),
                ('scoredetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeuroAI.scoredetails')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeuroAI.condition')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeuroAI.scoredetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeuroAI.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
