# Generated by Django 5.1.4 on 2025-01-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroAI', '0009_alter_response_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disorder',
            name='disorder',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disorder',
            name='exercise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disorder',
            name='meditation',
            field=models.CharField(max_length=100),
        ),
    ]
